return {
	jump = { name = "Jump", action = "jump", default = Enum.KeyCode.Space },
	moveUp = { name = "Move Up", action = "move", direction = "up", default = Enum.KeyCode.W },
	moveDown = { name = "Move Down", action = "move", direction = "down", default = Enum.KeyCode.S },
	moveLeft = { name = "Move Left", action = "move", direction = "left", default = Enum.KeyCode.A },
	moveRight = { name = "Move Right", action = "move", direction = "right", default = Enum.KeyCode.D },
}
