return {
	GAMEPAD_BUTTONS = {
		[Enum.KeyCode.ButtonA] = true,
		[Enum.KeyCode.ButtonB] = true,
		[Enum.KeyCode.ButtonX] = true,
		[Enum.KeyCode.ButtonY] = true,
		[Enum.KeyCode.ButtonL1] = true,
		[Enum.KeyCode.ButtonL2] = true,
		[Enum.KeyCode.ButtonL3] = true,
		[Enum.KeyCode.ButtonR1] = true,
		[Enum.KeyCode.ButtonR2] = true,
		[Enum.KeyCode.ButtonR3] = true,
		[Enum.KeyCode.DPadUp] = true,
		[Enum.KeyCode.DPadDown] = true,
		[Enum.KeyCode.DPadLeft] = true,
		[Enum.KeyCode.DPadRight] = true,
		[Enum.KeyCode.ButtonStart] = true,
		[Enum.KeyCode.ButtonSelect] = true,
	},
	MOUSE_BUTTONS = {
		[Enum.UserInputType.MouseButton1] = true,
		[Enum.UserInputType.MouseButton2] = true,
		[Enum.UserInputType.MouseButton3] = true,
	},
}
